### ISSUE TITLE
Use Rust formatting

### ISSUE THREAD

**Issue by Nashtare** [toposware/frost#41]
Given the increasing differences there are with the original repository (+ it seems it has been abandoned?), we may want to apply rustfmt to be consistent with the rest of our codebase, and insert back the rule in the CI jobs.

**Comment by Nashtare** [comment]
Any thoughts on this @hadjiszs @Freyskeyd? The upstream repo is clearly abandoned, we've made two major updates to the original FROST construction, bringing us quite away from it, and some portions of the codebase really hurt my eyes..

**Comment by Freyskeyd** [comment]
I'm OK to apply a Rustfmt if the upstream repository is abandoned. And yes, if we clean up the code style, we need to enforce these rules by using fmt Github actions.
